# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Aditya/ece385/final_project/ddr3_test/ddr3test/ddr3test.srcs/sources_1/bd/ddr3_controller/ip/ddr3_controller_auto_pc_1/ddr3_controller_auto_pc_1.xci
# IP: The module: 'ddr3_controller_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aditya/ece385/final_project/ddr3_test/ddr3test/ddr3test.gen/sources_1/bd/ddr3_controller/ip/ddr3_controller_auto_pc_1/ddr3_controller_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_controller_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Aditya/ece385/final_project/ddr3_test/ddr3test/ddr3test.srcs/sources_1/bd/ddr3_controller/ip/ddr3_controller_auto_pc_1/ddr3_controller_auto_pc_1.xci
# IP: The module: 'ddr3_controller_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aditya/ece385/final_project/ddr3_test/ddr3test/ddr3test.gen/sources_1/bd/ddr3_controller/ip/ddr3_controller_auto_pc_1/ddr3_controller_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr3_controller_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
