# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/urbana_ddr3_provided/urbana_ddr3.xdc

# Block Designs: bd/ddr3_controller/ddr3_controller.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller || ORIG_REF_NAME==ddr3_controller} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_microblaze_0_0/ddr3_controller_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_microblaze_0_0 || ORIG_REF_NAME==ddr3_controller_microblaze_0_0} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_mig_7series_0_1/ddr3_controller_mig_7series_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_mig_7series_0_1 || ORIG_REF_NAME==ddr3_controller_mig_7series_0_1} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_dlmb_v10_0/ddr3_controller_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_dlmb_v10_0 || ORIG_REF_NAME==ddr3_controller_dlmb_v10_0} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_ilmb_v10_0/ddr3_controller_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_ilmb_v10_0 || ORIG_REF_NAME==ddr3_controller_ilmb_v10_0} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_dlmb_bram_if_cntlr_0/ddr3_controller_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==ddr3_controller_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_ilmb_bram_if_cntlr_0/ddr3_controller_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==ddr3_controller_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_lmb_bram_0/ddr3_controller_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_lmb_bram_0 || ORIG_REF_NAME==ddr3_controller_lmb_bram_0} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_xbar_0/ddr3_controller_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_xbar_0 || ORIG_REF_NAME==ddr3_controller_xbar_0} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_auto_pc_3/ddr3_controller_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_auto_pc_3 || ORIG_REF_NAME==ddr3_controller_auto_pc_3} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_auto_pc_0/ddr3_controller_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_auto_pc_0 || ORIG_REF_NAME==ddr3_controller_auto_pc_0} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_auto_pc_1/ddr3_controller_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_auto_pc_1 || ORIG_REF_NAME==ddr3_controller_auto_pc_1} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_auto_pc_2/ddr3_controller_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_auto_pc_2 || ORIG_REF_NAME==ddr3_controller_auto_pc_2} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_microblaze_0_axi_periph_0/ddr3_controller_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_microblaze_0_axi_periph_0 || ORIG_REF_NAME==ddr3_controller_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_microblaze_0_axi_intc_0/ddr3_controller_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_microblaze_0_axi_intc_0 || ORIG_REF_NAME==ddr3_controller_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_microblaze_0_xlconcat_0/ddr3_controller_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_microblaze_0_xlconcat_0 || ORIG_REF_NAME==ddr3_controller_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_mdm_1_0/ddr3_controller_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_mdm_1_0 || ORIG_REF_NAME==ddr3_controller_mdm_1_0} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_rst_mig_7series_0_83M_0/ddr3_controller_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==ddr3_controller_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_axi_uartlite_0_0/ddr3_controller_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_axi_uartlite_0_0 || ORIG_REF_NAME==ddr3_controller_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/ddr3_controller/ip/ddr3_controller_axi_timer_0_0/ddr3_controller_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3_controller_axi_timer_0_0 || ORIG_REF_NAME==ddr3_controller_axi_timer_0_0} -quiet] -quiet

# XDC: c:/Users/Aditya/ece385/final_project/raycast_ddr3_v1/ddr3test/ddr3test.gen/sources_1/bd/ddr3_controller/ddr3_controller_ooc.xdc
